---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultapp-deployment
  labels:
    name: result-app
    auther: sai
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app
  template:
    metadata:
      name: resultapp-pod
      labels:
        name: result-app
    spec:
      containers:
        - name: my-resultapp
          image: dockersamples/examplevotingapp_result
...