---
apiVersion: v1
kind: Service
metadata:
  name: votingapp-serive
  labels:
    auther: sai
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: voting-app
...